[settings]
time_base = "Relative"
tick_quant = "8"
ticks_per_frame = 8
frame_min = 1
frame_max = 22
frame_start = 1

# LOOP (left)
[[script]]
run_at_frame = 11
action = "SetFrameNext"
frame_index = 2

# LOOP (right)
[[script]]
run_at_frame = 22
action = "SetFrameNext"
frame_index = 12

# Support left/right
[[script]]
run_on_slot_enable = "DirectionLeft"
action = "SetFrameNow"
frame_index = 1
[[script]]
run_on_slot_enable = "DirectionRight"
action = "SetFrameNow"
frame_index = 11

# Blink Red on Damage
[[script]]
run_every_n_ticks = "8+2"
require_slots_any = ["Damage"]
action = "SetSpriteColor"
color = "#ff0000"
[[script]]
run_every_n_ticks = "8+6"
require_slots_any = ["Damage"]
action = "SetSpriteColor"
color = "#ffffff"

# Ensure correct color after damage stops
[[script]]
run_on_slot_disable = "Damage"
action = "SetSpriteColor"
color = "#ffffff"

# On Damage, immediately change color to ensure no delay
[[script]]
run_on_slot_enable = "Damage"
action = "SetSpriteColor"
color = "#ff0000"