[settings]
time_base = "Relative"
tick_quant = "8"
ticks_per_frame = 8
frame_min = 1
frame_max = 24
frame_start = 1

[[script]]
run_on_playback_control = "Start"
if_previous_script_key = "anim.player.Fall"
action = "PlayAudio"
volume = 0.2
asset_key = "audio.game.FallImpact"

[[script]]
run_on_slot_enable = "DirectionLeft"
if_previous_script_key = "anim.player.Fall"
action = "SetFrameNow"
frame_index = 1

[[script]]
run_on_slot_enable = "DirectionRight"
if_previous_script_key = "anim.player.Fall"
action = "SetFrameNow"
frame_index = 13

# LOOP (left)
[[script]]
run_at_frame = 12
action = "SetFrameNext"
frame_index = 4

# LOOP (right)
[[script]]
run_at_frame = 24
action = "SetFrameNext"
frame_index = 15

# Support left/right
[[script]]
run_on_slot_enable = "DirectionLeft"
if_previous_script_key = "anim.player.Run"
action = "SetFrameNow"
frame_index = 3
[[script]]
run_on_slot_enable = "DirectionRight"
if_previous_script_key = "anim.player.Run"
action = "SetFrameNow"
frame_index = 15

# needed for expected flip behavior
[[script]]
run_on_slot_enable = "DirectionLeft"
action = "SetSpriteFlip"
flip_x = true
[[script]]
run_on_slot_enable = "DirectionRight"
action = "SetSpriteFlip"
flip_x = false

# Blink Red on Damage
[[script]]
run_every_n_ticks = "8+2"
require_slots_any = ["Damage"]
action = "SetSpriteColor"
color = "#ff0000"
[[script]]
run_every_n_ticks = "8+6"
require_slots_any = ["Damage"]
action = "SetSpriteColor"
color = "#ffffff"

# Ensure correct color after damage stops
[[script]]
run_on_slot_disable = "Damage"
action = "SetSpriteColor"
color = "#ffffff"

# On Damage, immediately change color to ensure no delay
[[script]]
run_on_slot_enable = "Damage"
action = "SetSpriteColor"
color = "#ff0000"
