[settings]
time_base = "Relative"
tick_quant = "8"
ticks_per_frame = 8
frame_min = 1
frame_max = 12
frame_start = 1


# INITIALIZE JUMP STRAIGHT
[[script]]
run_on_playback_control = "Start"
forbid_slots_all = ["MovingSideways"]
action = "SetFrameNow"
frame_index = 1

[[script]]
run_on_playback_control = "Start"
action = "PlayAudio"
volume = 0.5
asset_key = "audio.game.JumpStart"

#SWITCH FROM FORWARD TO STRAIGHT
[[script]]
run_at_frame = 7
forbid_slots_all = ["MovingSideways"]
action = "SetFrameNow"
frame_index = 1
[[script]]
run_at_frame = 8
forbid_slots_all = ["MovingSideways"]
action = "SetFrameNow"
frame_index = 2
[[script]]
run_at_frame = 9
forbid_slots_all = ["MovingSideways"]
action = "SetFrameNow"
frame_index = 3
[[script]]
run_at_frame = 10
forbid_slots_all = ["MovingSideways"]
action = "SetFrameNow"
frame_index = 4
[[script]]
run_at_frame = 11
forbid_slots_all = ["MovingSideways"]
action = "SetFrameNow"
frame_index = 5
[[script]]
run_at_frame = 12
forbid_slots_all = ["MovingSideways"]
action = "SetFrameNow"
frame_index = 6

# LOOP JUMP STRAIGHT
[[script]]
run_at_frame = 6
action = "SetFrameNext"
frame_index = 3


# Support left/right flipping
[[script]]
run_on_slot_enable = "DirectionLeft"
action = "SetSpriteFlip"
flip_x = true
[[script]]
run_on_slot_enable = "DirectionRight"
action = "SetSpriteFlip"
flip_x = false