[settings]
time_base = "Relative"
tick_quant = "8"
ticks_per_frame = 8
frame_min = 1
frame_max = 10
frame_start = 1

[[script]]
run_at_frame = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
require_slots_any = ["SerpentRing", "FrenziedAttack"]
action = "SetTicksPerFrame"
ticks_per_frame = 6

# LOOP
[[script]]
run_at_frame = 8
action = "SetFrameNext"
frame_index = 3

[[script]]
run_on_playback_control = "Start"
action = "PlayAudio"
asset_key = "audio.game.HammerWhirl"