atlas_asset_key = "anim.spider.RangedAttack.sprite"

[settings]
time_base = "Relative"
frame_start = 1
tick_quant = "8"
ticks_per_frame = 8
frame_max = 15
frame_min = 1

# LOOP
[[script]]
action = "SetFrameNext"
frame_index = 1
run_at_frame = 15

# Support left/right flipping
[[script]]
run_on_slot_enable = "DirectionLeft"
action = "SetSpriteFlip"
flip_x = true
[[script]]
run_on_slot_enable = "DirectionRight"
action = "SetSpriteFlip"
flip_x = false
