[settings]
time_base = "Relative"
tick_quant = "8"
ticks_per_frame = 8
frame_min = 1
frame_max = 20
frame_start = 1

[[script]]
run_on_slot_enable = "Damaged"
action = "PlayAudio"
volume = 0.7
asset_key = "audio.game.PlayerGetsDamaged"

[[script]]
run_on_slot_enable = "XpOrb"
action = "PlayAudio"
volume = 0.5
asset_key = "audio.game.XpOrbs"

[[script]]
run_at_frame = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
require_slots_any = ["SerpentRing", "FrenziedAttack"]
action = "SetTicksPerFrame"
ticks_per_frame = 6

[[script]]
run_at_frame = [2, 7, 12]
forbid_slots_all = ["AttackTransition"]
action = "PlayAudio"
volume = 0.5
asset_key = "audio.game.SwordSlash"

# play the last frame again if the animation hasnt ended so we dont roll over into next variant
[[script]]
run_at_frame = [5]
action = "SetFrameNext"
frame_index = 5

[[script]]
run_at_frame = [10]
action = "SetFrameNext"
frame_index = 10

[[script]]
run_at_frame = [15]
action = "SetFrameNext"
frame_index = 15

# Transition from SwordBasicRun - consolidated into a single mapping
[[script]]
run_on_playback_control = "Start"
if_previous_script_key = "anim.player.SwordBasicRun"
if_oldanim_frame_was = [1, 2, 3, 4, 5, 6, 7, 8]
action = "SetFrameNow"
frame_index = [1, 2, 3, 4, 6, 7, 8, 9]

# Transition from SwordBasicAir - consolidated into a single mapping
[[script]]
run_on_playback_control = "Start"
if_previous_script_key = "anim.player.SwordBasicAir"
if_oldanim_frame_was = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
action = "SetFrameNow"
frame_index = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

# VARIANT 1 INIT
[[script]]
run_on_playback_control = "Start"
forbid_slots_all = ["AttackTransition"]
action = "SetFrameNow"
frame_index = 1

# VARIANT 2 INIT
[[script]]
run_on_playback_control = "Start"
forbid_slots_all = ["AttackTransition"]
if_runcount_quant = "2"
action = "SetFrameNow"
frame_index = 6

# VARIANT 3 INIT
[[script]]
run_on_playback_control = "Start"
forbid_slots_all = ["AttackTransition"]
if_runcount_quant = "17"
action = "SetFrameNow"
frame_index = 11

# VARIANT 3.2 INIT (to create polyrhythm)
[[script]]
run_on_playback_control = "Start"
forbid_slots_all = ["AttackTransition"]
if_runcount_quant = "10"
action = "SetFrameNow"
frame_index = 11

# Support left/right flipping
[[script]]
run_on_slot_enable = "DirectionLeft"
action = "SetSpriteFlip"
flip_x = true
[[script]]
run_on_slot_enable = "DirectionRight"
action = "SetSpriteFlip"
flip_x = false
