[settings]
time_base = "Relative"
tick_quant = "8"
ticks_per_frame = 8
frame_min = 1
frame_max = 20
frame_start = 1

# VARIANT 1 INIT
[[script]]
run_on_playback_control = "Start"
action = "SetFrameNow"
frame_index = 1

# VARIANT 2 INIT
[[script]]
run_on_playback_control = "Start"
if_runcount_quant = "2"
action = "SetFrameNow"
frame_index = 5

# Support left/right flipping
[[script]]
run_on_slot_enable = "DirectionLeft"
action = "SetSpriteFlip"
flip_x = true
[[script]]
run_on_slot_enable = "DirectionRight"
action = "SetSpriteFlip"
flip_x = false

# Blink Red on Damage
[[script]]
run_every_n_ticks = "8+2"
require_slots_any = ["Damage"]
action = "SetSpriteColor"
color = "#ff0000"
[[script]]
run_every_n_ticks = "8+6"
require_slots_any = ["Damage"]
action = "SetSpriteColor"
color = "#ffffff"

# Ensure correct color after damage stops
[[script]]
run_on_slot_disable = "Damage"
action = "SetSpriteColor"
color = "#ffffff"

# On Damage, immediately change color to ensure no delay
[[script]]
run_on_slot_enable = "Damage"
action = "SetSpriteColor"
color = "#ff0000"
