[settings]
time_base = "Relative"
tick_quant = "8"
ticks_per_frame = 8
frame_min = 1
frame_max = 6
frame_start = 5

[[script]]
run_at_frame = [5]
action = "PlayAudio"
asset_key = "audio.game.HammerImpact"
