[settings]
time_base = "Relative"
tick_quant = "8"
ticks_per_frame = 8
frame_min = 1
frame_max = 6
frame_start = 1

[[script]]
run_at_frame = [1, 2, 3, 4, 5, 6]
require_slots_any = ["SerpentRing", "FrenziedAttack"]
action = "SetTicksPerFrame"
ticks_per_frame = 6

# LOOP
[[script]]
run_at_frame = 5
action = "SetFrameNext"
frame_index = 2

[[script]]
run_on_playback_control = "Start"
action = "PlayAudio"
asset_key = "audio.game.SwordWhirl"

# Blink Red on Damage
[[script]]
run_every_n_ticks = "8+2"
require_slots_any = ["Damage"]
action = "SetSpriteColor"
color = "#ff0000"
[[script]]
run_every_n_ticks = "8+6"
require_slots_any = ["Damage"]
action = "SetSpriteColor"
color = "#ffffff"

# Ensure correct color after damage stops
[[script]]
run_on_slot_disable = "Damage"
action = "SetSpriteColor"
color = "#ffffff"

# On Damage, immediately change color to ensure no delay
[[script]]
run_on_slot_enable = "Damage"
action = "SetSpriteColor"
color = "#ff0000"
