[settings]
time_base = "Relative"
tick_quant = "8"
ticks_per_frame = 8
frame_min = 1
frame_max = 8
frame_start = 3

[[script]]
run_at_frame = [1, 2, 3, 4, 5, 6, 7, 8]
require_slots_any = ["SerpentRing", "FrenziedAttack"]
action = "SetTicksPerFrame"
ticks_per_frame = 6

# VARIANT 1 INIT
[[script]]
run_on_playback_control = "Start"
forbid_slots_all = ["AttackTransition"]
action = "SetFrameNow"
frame_index = 1

[[script]]
run_at_frame = [1]
action = "PlayAudio"
asset_key = "audio.game.BowShoot"

# Support left/right flipping
[[script]]
run_on_slot_enable = "DirectionLeft"
action = "SetSpriteFlip"
flip_x = true
[[script]]
run_on_slot_enable = "DirectionRight"
action = "SetSpriteFlip"
flip_x = false
